version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3000"  # Mapeando a porta 3000 do contêiner para a porta 3001 no host
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
