// https://servicodados.ibge.gov.br/api/docs/localidades#api-UFs-estadosGet
// properties transalted to english
export const states = [
  {
    id: 12,
    code: "AC",
    name: "Acre",
    region: { id: 1, code: "N", name: "Norte" },
  },
  {
    id: 27,
    code: "AL",
    name: "Alagoas",
    region: { id: 2, code: "NE", name: "Nordeste" },
  },
  {
    id: 16,
    code: "AP",
    name: "Amapá",
    region: { id: 1, code: "N", name: "Norte" },
  },
  {
    id: 13,
    code: "AM",
    name: "Amazonas",
    region: { id: 1, code: "N", name: "Norte" },
  },
  {
    id: 29,
    code: "BA",
    name: "Bahia",
    region: { id: 2, code: "NE", name: "Nordeste" },
  },
  {
    id: 23,
    code: "CE",
    name: "Ceará",
    region: { id: 2, code: "NE", name: "Nordeste" },
  },
  {
    id: 53,
    code: "DF",
    name: "Distrito Federal",
    region: { id: 5, code: "CO", name: "Centro-Oeste" },
  },
  {
    id: 32,
    code: "ES",
    name: "Espírito Santo",
    region: { id: 3, code: "SE", name: "Sudeste" },
  },
  {
    id: 52,
    code: "GO",
    name: "Goiás",
    region: { id: 5, code: "CO", name: "Centro-Oeste" },
  },
  {
    id: 21,
    code: "MA",
    name: "Maranhão",
    region: { id: 2, code: "NE", name: "Nordeste" },
  },
  {
    id: 51,
    code: "MT",
    name: "Mato Grosso",
    region: { id: 5, code: "CO", name: "Centro-Oeste" },
  },
  {
    id: 50,
    code: "MS",
    name: "Mato Grosso do Sul",
    region: { id: 5, code: "CO", name: "Centro-Oeste" },
  },
  {
    id: 31,
    code: "MG",
    name: "Minas Gerais",
    region: { id: 3, code: "SE", name: "Sudeste" },
  },
  {
    id: 15,
    code: "PA",
    name: "Pará",
    region: { id: 1, code: "N", name: "Norte" },
  },
  {
    id: 25,
    code: "PB",
    name: "Paraíba",
    region: { id: 2, code: "NE", name: "Nordeste" },
  },
  {
    id: 41,
    code: "PR",
    name: "Paraná",
    region: { id: 4, code: "S", name: "Sul" },
  },
  {
    id: 26,
    code: "PE",
    name: "Pernambuco",
    region: { id: 2, code: "NE", name: "Nordeste" },
  },
  {
    id: 22,
    code: "PI",
    name: "Piauí",
    region: { id: 2, code: "NE", name: "Nordeste" },
  },
  {
    id: 33,
    code: "RJ",
    name: "Rio de Janeiro",
    region: { id: 3, code: "SE", name: "Sudeste" },
  },
  {
    id: 24,
    code: "RN",
    name: "Rio Grande do Norte",
    region: { id: 2, code: "NE", name: "Nordeste" },
  },
  {
    id: 43,
    code: "RS",
    name: "Rio Grande do Sul",
    region: { id: 4, code: "S", name: "Sul" },
  },
  {
    id: 11,
    code: "RO",
    name: "Rondônia",
    region: { id: 1, code: "N", name: "Norte" },
  },
  {
    id: 14,
    code: "RR",
    name: "Roraima",
    region: { id: 1, code: "N", name: "Norte" },
  },
  {
    id: 42,
    code: "SC",
    name: "Santa Catarina",
    region: { id: 4, code: "S", name: "Sul" },
  },
  {
    id: 35,
    code: "SP",
    name: "São Paulo",
    region: { id: 3, code: "SE", name: "Sudeste" },
  },
  {
    id: 28,
    code: "SE",
    name: "Sergipe",
    region: { id: 2, code: "NE", name: "Nordeste" },
  },
  {
    id: 17,
    code: "TO",
    name: "Tocantins",
    region: { id: 1, code: "N", name: "Norte" },
  },
];
