export const csvHeaders = {
  id: "Id",
  createdAt: "Criado em",
  updatedAt: "Atualizado em",
  link: "Link",
  proposition: "Proposição",
  "propositionType.description": "Tipo proposição",
  number: "Número",
  year: "Ano",
  "house.description": "Casa",
  author: "Autor",
  presentationDate: "Ano de Apresentação",
  // ementa: "Ementa",
  significance: "Significância",
  "situation.description": "Situação",
  archived: "Arquivado",
  approvalProbability: "Probabilidade aprovação",
  commisions: "Comissoes",
  regime: "Regime",
  "theme.description": "Tema",
  "project.description": "Projeto",
};
