name: Deploy project
on:
  push:
    branches:
      - main
      # - dev

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: choice
        required: true
        # default: "development"
        default: "production"
        options:
          # - "development"
          - "production"

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Testing
        run: yarn test --passWithNoTests

      - name: Build
        run: yarn build

      - name: Docker Login - Azure Container Registry
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}

      - name: Build and push the image
        run: |
          docker build . -t ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/observatorio-brasil/monitoring-front
          docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/observatorio-brasil/monitoring-front

      # - name: Build and push the image - DEV
      #   if: github.event.inputs.environment == 'development' || github.ref_name != 'main'
      #   run: |
      #     docker build . -t observatorio-brasil/monitoring-front
      #     docker push observatorio-brasil/monitoring-front
