name: Deploy Observatorio Portal to DEV Environment

on:
  push:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

    - name: Create Env
      run: echo "NEXT_PUBLIC_MONITORING_API_URL=https://monitoring-proposition-api-dev.azurewebsites.net/api" > .env

    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/observatorio-brasil/portal-observatorio-dev

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/observatorio-brasil/portal-observatorio-dev

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'portal-observatorio-dev'
        slot-name: 'production'
        images: '${{ secrets.DOCKER_CONTAINER_REGISTRY }}/observatorio-brasil/portal-observatorio-dev'
